spring.application.name=helloworld-backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/studentdb
spring.datasource.username=amrit
spring.datasource.password=amrit@123

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect