spring.application.name=helloworld-backend
server.port=8080

spring.datasource.url=//ep-quiet-bonus-anik26xd-pooler.c-6.us-east-1.aws.neon.tech/studentdb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_GTuKr1IiS5dF

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect